markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
nav:
  - Home: index.md
include:
  - docs/*.md
theme: minima
gems:
  - jekyll-toc
toc:
    min_level: 1
    max_level: 4
