markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
nav:
  - Home: index.md
include:
  - docs/*.md
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

