markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
theme: jekyll-theme-chirpy
plugins:
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-latex
# Set this to true to get LaTeX math equation support
use_math: true
nav:
  - Home: index.md
include:
  - docs/*.md
