markdown: kramdown
kramdown:
  input: GFM
    #  parse_block_html: true
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
nav:
  - Home: index.md
include:
  - docs/*.md
    #remote_theme: sighingnow/jekyll-gitbook
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
syntax_highlighter_style: colorful
toc:
    enabled: true
    h_min: 1
    h_max: 3
